title: GaryStack
description: > # this means to ignore newlines until "baseurl:"
  黑夜中的太阳
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://garystack.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: Github
  link: "https://github.com/GaryStack"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/GaryStack
  

# Build settings
markdown: kramdown
permalink: pretty
